// <auto-generated />
using System;
using BlogPost.Api.src.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPost.Api.src.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BlogPostContext))]
    [Migration("20240619170520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("BlogPost.Api.src.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            Content = "This post covers the basics of C# programming language...",
                            CreatedDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            Content = "ASP.NET Core is a free and open-source web framework...",
                            CreatedDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding ASP.NET Core",
                            UpdatedDate = new DateTime(2023, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Emily Johnson",
                            Content = "Entity Framework Core (EF Core) is a lightweight, extensible...",
                            CreatedDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            Title = "Getting Started with Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Michael Brown",
                            Content = "This post explains how to deploy ASP.NET Core applications...",
                            CreatedDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deploying ASP.NET Core Applications",
                            UpdatedDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jessica White",
                            Content = "In this post, we explore some advanced C# programming techniques...",
                            CreatedDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Advanced C# Programming Techniques"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
